### ISSUE TITLE
Create grab/release functionality in the HatchController system

### ISSUE THREAD

**Issue by deaner8765** [MetalCowRobotics/Robot2019#32]
https://github.com/MetalCowRobotics/Robot2019/blob/95f18b58da208623585ee6bc96eb46ee830d798b/src/main/java/frc/systems/HatchHandler.java#L30

need to add the controls basic framework code for the device to open and close the hatch grabbing mechanism.

**Comment by metalcow-student** [comment]
This has been coded but I have not been able to test it yet because the pneumatics are not currently hooked up. The grab and release are mapped to pneumatic channels 2 and 3 and they are mapped as a toggle to the controller's 'B' button.
